

node('master') {
    def addg = ''
    
try {

if(currentBuild.getPreviousBuild() != null) {
 print("not")
} else {
	print("null")
}


    currentBuild.result = 'SUCCESS'
  }
  catch (err) {
    currentBuild.result = 'FAILURE'
  }
  finally {
   
    
  }
}